# Application settings
app_name: vasify-website
app_port: 8024
health_check_path: "/"
env: development

# Domain configuration
domain: vasifytech.com

# Target machine (must match inventory.yml)
target_host: vt-prod-app-02

# SSL settings
ssl_email: yogendra@vasifytech.com

# Docker registry (GitLab) 
registry: registry.gitlab.com
registry_image: registry.gitlab.com/vasify/client-projects/nordica-crm-canada
